-- Actual table
CREATE TABLE nablaweb_vue.nabla_group_members (
    "user" text NOT NULL,
    member_role text DEFAULT ''::text,
    "group" text NOT NULL,
    "order" integer NOT NULL,
    date_joined timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);

-- Save order by increment. Also handled (in my favourite hack of all time) by client
ALTER TABLE nablaweb_vue.nabla_group_members ALTER COLUMN "order" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME nablaweb_vue.nabla_group_members_order_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Constraints
ALTER TABLE ONLY nablaweb_vue.nabla_group_members ADD CONSTRAINT nabla_group_members_pkey PRIMARY KEY ("group", "user");
ALTER TABLE ONLY nablaweb_vue.nabla_group_members ADD CONSTRAINT unique_group_order UNIQUE ("group", "order");
ALTER TABLE ONLY nablaweb_vue.nabla_group_members ADD CONSTRAINT nabla_group_members_group_fkey FOREIGN KEY ("group") REFERENCES nablaweb_vue.nabla_groups(group_url);
ALTER TABLE ONLY nablaweb_vue.nabla_group_members ADD CONSTRAINT nabla_group_members_user_fkey FOREIGN KEY ("user") REFERENCES nablaweb_vue.nabla_users(username) ON UPDATE CASCADE;

-- Descriptions for Supabase Studio
COMMENT ON TABLE nablaweb_vue.nabla_group_members IS 'What members are part of what group';
COMMENT ON COLUMN nablaweb_vue.nabla_group_members."user" IS 'Member''s username';
COMMENT ON COLUMN nablaweb_vue.nabla_group_members.member_role IS 'Short user-editable string';
COMMENT ON COLUMN nablaweb_vue.nabla_group_members."group" IS 'The groups unique group_url';
COMMENT ON COLUMN nablaweb_vue.nabla_group_members."order" IS 'How a group shows its members';
COMMENT ON COLUMN nablaweb_vue.nabla_group_members.date_joined IS 'Date of first entry intro group';
COMMENT ON COLUMN nablaweb_vue.nabla_group_members.is_active IS 'Is member of group';